name: PR checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Run quick unit tests
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        pyver: ['3.10', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyver }}
    - name: Install flit
      run: pip install flit
    - name: Install pytket-qirpass
      run: flit install
    - name: Run quick tests
      run: python -m unittest test.test_qirpass
